twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        system_name: '%env(SYSTEM_NAME)%'
    form_themes:
        - 'form/fields.html.twig'
